#!/bin/bash
# Script to rename 'empty' to 'sqllogictest'.
# Change 'sqllogictest' to your desired project name,
# run this script,
# then delete it.

git ls-files |
    grep -v checker.xml |
    grep -v rename |
    xargs sed -i '' -e 's/Empty/SqlLogicTest/g;s/empty/sqllogictest/g'
git ls-files |
    grep -v checker.xml |
    grep -v rename |
    xargs sed -i '' -e 's/julianhyde/hydromatic/g;s/2022/2023/g'
for f in $(git ls-files); do
    g=$(echo $f | sed -e 's/Empty/SqlLogicTest/g;s/empty/sqllogictest/g')
    if [ "$f" != "$g" ]; then
        mkdir -p $(dirname $g)
        git mv $f $g
    fi
done

# End rename
