#!/bin/bash
#
# Copyright 2022 VMware, Inc.
# SPDX-License-Identifier: MIT
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#
# As a simple example, run this:
#
# ./slt -h
#

# Deduce whether we are running cygwin
case $(uname -s) in
(CYGWIN*) cygwin=true;;
(*) cygwin=;;
esac

# Build classpath on first call. (To force rebuild, remove classpath.txt.)
cd $(dirname $0)
if [ ! -f target/classpath.txt ]; then
  ./mvnw compile
  ./mvnw dependency:build-classpath -Dmdep.outputFile=target/classpath.txt
fi

CP="target/classes:target/test-classes:$(cat target/classpath.txt)"
VM_OPTS=
if [ "$cygwin" ]; then
  CP=$(cygpath -wp "$CP")
fi

#exec java $VM_OPTS -cp "${CP}" net.hydromatic.sqllogictest.Main "$@"
# TODO: how to programmatically get the jar name?
exec java -classpath target/sql-logic-test-0.2-SNAPSHOT.jar net.hydromatic.sqllogictest.Main "$@"

# End slt
